#!/bin/bash

xset mouse 3/2 0
xrdb -merge ~/.Xdefaults
xrdb -merge ~/XTerm
yeahconsole &
xscreensaver -no-splash &
eval "$(gpg-agent --daemon)"

{% for command in xinitrc_commands|default([]) %}
{{ command }}
{% else %}
[ -f ~/.xinitrc-local ] && . ~/.xinitrc-local
{% endfor %}

exec awesome
